
<div class="container">
  <h2>Edit Category</h2>
  <form name="form" method="POST" action="/categories/<?php echo $category->getId()?>/update">
    <div class="form-group">
      <label for="name">Name</label>
      <input type="text" class="form-control" id="name" name="name" placeholder="Enter your name" value="<?php echo $category->getName(); ?>">
    </div>
    <button type="submit" class="btn btn-default">Submit</button>
  </form>
</div>