<?php include __DIR__.'/../header.phtml'; ?>

<div class="container">
    <div class="row">
        <h3>Listagem de Categorias</h3>
        <table class="table">
            <thead>
                <tr>
                    <th>ID</th>
                    <th>Categoria</th>
                </tr>                
            </thead>
            <tbody>
                <tr>
                    
                </tr>
            </tbody>
        </table>
    </div>
</div>

<?php include __DIR__.'/../footer.phtml'; ?>